### ISSUE TITLE
Descriptions and photographs

### ISSUE THREAD

**Issue by flecktarn121** [Arquisoft/dechat_en2a#111]
Post here a short description of yourselves and a photograph to be shown in the manual.

**Comment by tgperry** [comment]
My name is Thomas Perry and I am a second year student from the United States studying for a semester at the University of Oviedo Software Engineering campus. While in the States, I attend Colorado School of Mines and study Computer Science and Analytical Statistics with a focus on Data Science. On this project, I focused mainly on front-end development in order to ensure a smooth user experience while using the application. When not in front of the computer, I enjoy camping, cooking, and shooting landscape photography worldwide, but especially in my home state of Washington.
![perry](https://user-images.githubusercontent.com/43394562/56749174-80271d80-6781-11e9-861d-99e897192f88.jpg)

**Comment by AlvasanG** [comment]
My name is Alvaro Sanchez, third year student at the University of Oviedo. Even if this project lands really outside of my comfort zone I have discovered a whole new world on my future field of expertise. I love computers as a whole, videogames, spending time with my friends and my music. My beside book is Sun Tzu's Art of War.

![perfil-uniovi](https://user-images.githubusercontent.com/26725408/56869383-5891b880-6a00-11e9-9397-0d3f08c3de2f.jpg)

**Comment by YerayG** [comment]
My name is Yeray and I am a third year Software Engineering student at the University of Oviedo. I have been working on this project of ours for some months, mainly focusing on functionality features and testing. Besides computers and technology, I love sports, language learning, playing and listening to music and experiencing other forms of art such as videogames, books and movies.
![face_i](https://user-images.githubusercontent.com/36376842/56869925-ecb34e00-6a07-11e9-8615-916267a5b217.jpg)

**Comment by josecurioso** [comment]
My name is Jose Manuel, josecurioso on everything important in life (mainly Steam and the internet). My hobbies include but are not limited to reading, long bike rides (like weeks long), climbing, mountaineering, playing video games and travelling (who doesn't like travelling). I never turn down a crazy adventure be it a trip to wherever we end up or a vivac night in the middle of nowhere. 
Regarding the project I have taken on the coordination role of the team, I enjoy learning about new technologies and I have discovered a new world with the Javascript/Typescript-based stacks.
(Disclaimer: the resolution and orientation of the photo are intentional)
![low poly](https://user-images.githubusercontent.com/9164105/56871504-293e7400-6a1f-11e9-9b3c-7ed0011c2d59.jpg)

**Comment by pastrana98** [comment]
My name is Luis, third year student at the University of Oviedo.
In west Asturias studied and raised.
On the Pc was where I spent most of my days.
Chillin out, maxin', relaxin' all cool
And writing some code 4 the school.

![WhatsApp Image 2019-04-29 at 02 20 33](https://user-images.githubusercontent.com/44980298/56872091-67d72d00-6a25-11e9-9d8f-d1170ec95300.jpeg)
