### ISSUE TITLE
Message deletion

### ISSUE THREAD

**Issue by YerayG** [Arquisoft/dechat_en2a#27]
We should implement the necessary functionality in order to delete messages

**Comment by josecurioso** [comment]
For using rdflib in our environment  [this](https://solid.inrupt.com/docs/manipulating-ld-with-rdflib) tutorial is highly recommended. Specially the part about he updateManager and its wonders for inserting/**deleting** triples.

**Comment by YerayG** [comment]
It is somewhat done but we need to look a little bit further into improving the way we retrieve the message URI for its deletion.

**Comment by josecurioso** [comment]
I have been checking out the code today for message deletion and fixed a small problem with concat instead using push now.
I also fixed a problem on the message loading function I had coded so that it now stores the message URI on the message object so in order to retrieve it now you only need to read it  from the object.

**Comment by YerayG** [comment]
All problems seem gone and everything is working properly so I am closing the issue for now.
