### ISSUE TITLE
Investigate what cfg is and also whats idp is and for what are they used for.

### ISSUE THREAD

**Issue by EnriqueJRodriguez** [Arquisoft/dechat_en2a#37]
In order to finish the login process in the terminal brach we need to provide to solid-auth-cli a idp.

**Comment by AlvasanG** [comment]
An "IdP" is an identity provider. 

It is a system that creates, maintains and manages identity information for principals while providing authentication services to relying applications. [Source](https://en.wikipedia.org/wiki/Identity_provider)

From Solid point of view, it can be used to gain some exposure as a Solid-compiant service. [Here](https://solid.github.io/solid-idps/) there is a list of the actualy Solid-compliant IdPs. In order to apply to be inside that list we should first complete the whole application.

As denoted [here](https://github.com/solid/solid-idp-list/), all that is needed is to configure a JSON file with the information required, pull request our proposal and wait for it to be approved.

Personally as I have stated before we could write the JSON file as of know, but we would not be eligible for IdP as of now.

**Comment by AlvasanG** [comment]
As of cfg, it is the configuration file our application will be using.

Nowadays it is generally written using JSON, but plain text has been an option since the beginning of programs. The preference of JSON (XML, YAML) over plain text comes as a form of serializing the format, making it both easier for the user to change the configuration to meet his needs and to ease the work the programmer must do in order to parse the cfg file.

**Comment by EnriqueJRodriguez** [comment]
Okay, I will continue researching for the terminal implementation.
